# Generated by Django 4.2.4 on 2023-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wasteplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteplan',
            name='image',
            field=models.FileField(blank=True, default='waste_plan_default.jpg', null=True, upload_to='waste_plan'),
        ),
    ]
