# Generated by Django 4.2.4 on 2023-08-24 12:33

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wasteplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedwaste',
            name='cwid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='ceid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='cpid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='wiid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix=''),
        ),
        migrations.AddField(
            model_name='wasteplan',
            name='wpid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
    ]
