# Generated by Django 4.2.4 on 2023-08-24 12:38

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_collectedwaste_cwid_collectionevent_ceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectedwaste',
            name='cwid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=5, max_length=20, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='ceid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=5, max_length=20, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='cpid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=5, max_length=20, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='wiid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=5, max_length=20, prefix=''),
        ),
        migrations.AlterField(
            model_name='wasteplan',
            name='wpid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=5, max_length=20, null=True, prefix=''),
        ),
    ]
