# Generated by Django 4.2.4 on 2023-08-24 12:47

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_collectionpoint_slug_wastecategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=5, max_length=20, null=True, prefix='')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('initiated', 'Initiated'), ('processing', 'Processing'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waste_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wasteplan')),
            ],
        ),
    ]
