# Generated by Django 4.2.4 on 2023-08-25 23:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_wasteorder_address_wasteorder_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteorder',
            name='collected_status',
            field=models.CharField(choices=[('Collected', 'Collected'), ('Not Collected', 'Not Collected'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress')], default='Not Collected', max_length=20),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='date_to_be_collected',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='message_to_subscriber',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='wasteorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
