# Generated by Django 4.2.4 on 2023-08-26 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_employee_collected_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New Subscriber', 'New Subscriber'), ('Collection Date Scheduled', 'Collection Date Scheduled'), ('Collection Cancelled', 'Collection Cancelled'), ('New Collection Job', 'New Collection Job')], default='New Subscriber', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=5, max_length=20, null=True, prefix='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wasteorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waste_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wasteplan')),
            ],
        ),
    ]
