# Generated by Django 4.2.4 on 2023-08-27 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_collectionpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Subscriber', 'New Subscriber'), ('Collection Date Scheduled', 'Collection Date Scheduled'), ('Collection Cancelled', 'Collection Cancelled'), ('New Collection Job', 'New Collection Job'), ('New Driving Job', 'New Driving Job'), ('Waste Collected', 'Waste Collected')], default='New Subscriber', max_length=100),
        ),
    ]
