# Generated by Django 4.2.4 on 2023-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_donation_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Subscriber', 'New Subscriber'), ('Collection Date Scheduled', 'Collection Date Scheduled'), ('Collection Cancelled', 'Collection Cancelled'), ('New Collection Job', 'New Collection Job'), ('New Driving Job', 'New Driving Job'), ('Waste Collected', 'Waste Collected'), ('New Donation', 'New Donation')], default='New Subscriber', max_length=100),
        ),
    ]
