# Generated by Django 4.2.4 on 2023-08-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='affiliate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seller',
        ),
    ]
