# Generated by Django 4.2.4 on 2023-08-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_remove_profile_affiliate_remove_profile_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
